name: andrew batt-rawden
favicon: null
layout_spectrum: 0.24843
typography_spectrum: 0.1972
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a8a297'
    - '#625f51'
    - '#222127'
    - '#9beaed'
  brandStrength: 0
  lightness: 0.8020273346919566
  saturation: 0
  rhythmicContrast: 1
purpose: []
